services:
  web:
    build: .
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/opt/odoo/addons
      - ./odoo:/opt/odoo/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo-web-data:/var/lib/odoo
    command: ["python3", "odoo-bin", "-c", "/etc/odoo/odoo.conf"]

  db:
    image: postgres:15
    container_name: odoo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
